[selection]
fg = "magenta"
bold = true

[visual_mode_selection]
fg = "red"
bold = true

[selection.prefix]
prefix = "  "
size = 2

[executable]
fg = "green"
bold = true

[regular]
fg = "light_white"

[directory]
fg = "blue"
bold = true

[link]
fg = "cyan"
bold = true

[link_invalid]
fg = "red"
bold = true

[socket]
fg = "light_white"
bold = true

[ext]

bmp.fg = "yellow"
gif.fg = "yellow"
heic.fg = "yellow"
jpg.fg = "yellow"
jpeg.fg = "yellow"
pgm.fg = "yellow"
png.fg = "yellow"
ppm.fg = "yellow"
svg.fg = "yellow"

wav.fg = "magenta"
flac.fg = "magenta"
mp3.fg = "magenta"
amr.fg = "magenta"

avi.fg = "magenta"
flv.fg = "magenta"
m3u.fg = "magenta"
m4a.fg = "magenta"
m4v.fg = "magenta"
mkv.fg = "magenta"
mov.fg = "magenta"
mp4.fg = "magenta"
mpg.fg = "magenta"
rmvb.fg = "magenta"
webm.fg = "magenta"
wmv.fg = "magenta"

7z.fg = "red"
bz2.fg = "red"
gz.fg = "red"
rar.fg = "red"
tar.fg = "red"
tgz.fg = "red"
xz.fg = "red"
zip.fg = "red"
