[templates.ags]
input_path = '~/.config/matugen/templates/ags.scss'
output_path = '~/.config/ags/scss/colors.scss'
mode = "Dark" # First letter MUST be upper-case

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
mode = "Dark" # First letter MUST be upper-case

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
mode = "Dark" # First letter MUST be upper-case

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'
mode = "Dark" # First letter MUST be upper-case

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'
mode = "Dark" # First letter MUST be upper-case

[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
swww_options = [
	"--transition-step",
	"10",
	"--transition-fps",
	"90"
]
prefix = '@'
# run_after = [
#     [ "echo", "'hello'" ],
#     [ "echo", "'hello again'" ],
# ]

[config.reload_apps_list]
kitty = true
gtk_theme = true
