#!/bin/bash

entries="⇠ Logout\n⏾ Suspend\n Reboot\n⏻ Shutdown"

selected=$(echo -e $entries|wofi --width 280 --height 250 --dmenu --style ~/.config/wofi/style.css --conf ~/.config/wofi/configPowerMenu --cache-file /dev/null | awk '{print tolower($2)}')

case $selected in
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
