[[color]]
name="red"
value="#f38ba8"
blend=true

[[color]]
name="orange"
value="#fab387"
blend=true

[[color]]
name="yellow"
value="#f9e2af"
blend=false
darkTone=92

[[color]]
name="green"
value="#a6e3a1"
blend=false

[[color]]
name="teal"
value="#94e2d5"
blend=false

[[color]]
name="blue"
value="#89b4fa"
blend=true

[[color]]
name="magenta"
value="#cba6f7"
blend=true

[[color]]
name="brown"
value="#f2cdcd"
blend=false
