[[item]]
file = "~/.config/ags/scss/colors.scss"
template = "ags"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"

[[item]]
file = "~/.config/hypr/colors.conf"
template = "hypr"

[[item]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
hook = "kill -SIGUSR1 $(pgrep kitty)"

[[item]]
file = "~/.vscode/extensions/undefined_publisher.materialyou-theme-0.0.1/themes/Material You-color-theme.json"
template = "vscode"

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"

[[item]]
file = "~/.config/gtk-4.0/gtk.css"
template = "gtk"
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark"

[[item]]
file = "~/.config/nvim/lua/custom/themes/materialyou.lua"
template = "nvim"

[[item]]
file = "~/.config/yazi/theme.toml"
template = "yazi"

[[item]]
file = "~/.mozilla/firefox/eppwtee1.default-release/chrome/firefox-gnome-theme/theme/colors/dark.css"
template = "firefox"

[[item]]
file = "~/.config/tmux/plugins/catppuccin-tmux/catppuccin-latte.tmuxtheme"
template = "tmux"
hook = "tmux source ~/.config/tmux/tmux.conf"

[[item]]
file = "~/.dotfiles_wayland/additional/new-tab-page/css/colors.css"
template = "newtab"

